#!/bin/bash
VER=$1
# Controlla se la variabile VER è vuota
if [ -z "$VER" ]; then
  echo "Errore: è necessario specificare un numero di versione."
  echo "Uso: $0 <versione>"
  exit 1
fi
cp ./deb/pool/main/penguins-eggs*$VER*amd64.deb ../penguins-eggs-ppa/dists/amd64
cp ./deb/pool/main/penguins-eggs*$VER*arm64.deb ../penguins-eggs-ppa/dists/arm64
cp ./deb/pool/main/penguins-eggs*$VER*i386.deb ../penguins-eggs-ppa/dists/i386